import { create } from 'zustand'

export const useGameStore = create((set) => ({
  players: [],
  winner: null,
  winnerId: null,
  winnerColor: null,
  locked: false,
  buzzOrder: [],
  currentTrack: null,
  scores: {},
  awaitingChoice: false,
  totalRounds: 0,
  currentRound: 0,
  gameOver: false,
  myId: null,
  myColor: null,

  setMyId: (id) => set({ myId: id }),
  setMyColor: (color) => set({ myColor: color }),

  applyState: (msg) => set({
    players: msg.players || [],
    winner: msg.winner || null,
    winnerId: msg.winnerId || null,
    winnerColor: msg.winnerColor || null,
    locked: !!msg.locked,
    buzzOrder: msg.buzzOrder || [],
    currentTrack: msg.currentTrack || null,
    scores: msg.scores || {},
    awaitingChoice: !!msg.awaitingChoice,
    totalRounds: msg.totalRounds || 0,
    currentRound: msg.currentRound || 0,
    gameOver: !!msg.gameOver,
  }),

  fullReset: () => set({
    players: [],
    winner: null,
    winnerId: null,
    winnerColor: null,
    locked: false,
    buzzOrder: [],
    currentTrack: null,
    scores: {},
    awaitingChoice: false,
    totalRounds: 0,
    currentRound: 0,
    gameOver: false,
    myId: null,
    myColor: null,
  }),
}))
